apiVersion: v1
data:
  accounts.emmanuel: apiKey, login
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  application.sync.impersonation.enabled: "false"
  exec.enabled: "false"
  kustomize.buildOptions: --enable-helm
  server.rbac.log.enforce.enable: "false"
  statusbadge.enabled: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  url: https://urban-rotary-phone-j7w7vqgp5rx2ppvp-30272.app.github.dev
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"accounts.emmanuel":"apiKey, login","admin.enabled":"true","application.instanceLabelKey":"argocd.argoproj.io/instance","application.sync.impersonation.enabled":"false","exec.enabled":"false","kustomize.buildOptions":"--enable-helm","server.rbac.log.enforce.enable":"false","statusbadge.enabled":"false","timeout.hard.reconciliation":"0s","timeout.reconciliation":"180s","url":"https://urban-rotary-phone-j7w7vqgp5rx2ppvp-30272.app.github.dev"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"argocd","meta.helm.sh/release-namespace":"argocd"},"creationTimestamp":"2025-11-09T06:23:01Z","labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd","app.kubernetes.io/version":"v2.14.10","helm.sh/chart":"argo-cd-7.8.26"},"name":"argocd-cm","namespace":"argocd","resourceVersion":"994","uid":"a422d082-1c82-4e1d-84d2-ffde9aeb06bb"}}
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2025-11-09T06:23:01Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.14.10
    helm.sh/chart: argo-cd-7.8.26
  name: argocd-cm
  namespace: argocd
  resourceVersion: "1974"
  uid: a422d082-1c82-4e1d-84d2-ffde9aeb06bb
